# Data Science z Python 3.10. Metryki i ocena modeli
## 🇬🇧 Data Science with Python 3.10. Metrics and models evaluation
#### 👨‍🏫 PhD Wojciech Oronowicz-Jaśkowiak
#### 🤖 https://github.com/aipogodzinach

### 1. Import bibliotek
#### 🇬🇧 Import libraries

In [ ]:
import os
import pandas as pd
import tensorflow as tf

from keras.models import Sequential
from keras.layers import Dense

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

import pandas as pd
import numpy as np
import matplotlib as plt
import os
import matplotlib.pyplot as plt
import seaborn as sns
import pickle

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
os.chdir('/content/drive/My Drive/PUM05')

Mounted at /content/drive


### 2.Przygotowanie danych
#### 🇬🇧 Data preparation

In [ ]:
os.getcwd()

base_data = pd.read_csv("DSP_1.csv")
base_data.columns
cols = ["Survived", "Pclass", "Sex", "Age", "SibSp", "Parch", "Fare", "Embarked"]
data = base_data[cols].copy()

data["Age"].fillna((data["Age"].mean()), inplace=True)
data.dropna(subset=['Embarked'], inplace=True)

encoder = LabelEncoder()
data.loc[:,"Sex"] = encoder.fit_transform(data.loc[:,"Sex"])
data.loc[:,"Embarked"] = encoder.fit_transform(data.loc[:,"Embarked"])

y = data.iloc[:,0]
x = data.iloc[:,1:8]
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

### Zadanie

#### 1. Wykorzystaj poniższy kod, żeby wytrenować cztery modele ML korzystając z zaproponowanych architektu sieci neuronowych. Uzupełnij kod dodając do niego zaproponowaną przez siebie architekturę sieci neuronowej.

In [ ]:
def model(X_train, y_train):

    forest = RandomForestClassifier (n_estimators=20, random_state=0)
    forest.fit(X_train,y_train)
    print("Random Forest: {0}".format(forest.score(X_train,y_train)))

    lreg = LogisticRegression(max_iter = 1000)
    lreg.fit(X_train,y_train)
    print("Regresja logistyczna: {0}".format(lreg.score(X_train,y_train)))

    tree = DecisionTreeClassifier()
    tree.fit(X_train,y_train)
    print("Decision Tree: {0}".format(tree.score(X_train,y_train)))

    from keras.layers import Dropout
    from tensorflow.keras.utils import to_categorical

    neuralnetwork = Sequential([
        Dense(9, kernel_initializer= 'uniform', activation='relu', input_dim = 7),
        Dense(9, kernel_initializer= 'uniform', activation='relu'),
        Dense(9, kernel_initializer= 'uniform', activation='relu'),
        Dense(5, kernel_initializer= 'uniform', activation='relu'),
        Dense(1, kernel_initializer= 'uniform', activation='sigmoid')
    ])

    neuralnetwork.compile(
        optimizer='adam',
        loss='binary_crossentropy',
        metrics=['accuracy'],
    )

    neuralnetwork.fit(
        X_train,
        y_train,
        epochs=50,
        batch_size=32,
    )

    print(X_train)
    print(y_train)

    evaluate = neuralnetwork.evaluate(
      x=X_train,
      y=y_train,
      batch_size=None,
      verbose="auto",
      sample_weight=None,
      steps=None,
      callbacks=None,
      max_queue_size=10,
      workers=1,
      use_multiprocessing=False,
      return_dict=False
)

    print("Neural network: {0}".format(evaluate))

    return forest, lreg, tree, neuralnetwork

forest, lreg, tree, neuralnetwork = model(X_train,y_train)

Random Forest: 0.980309423347398
Regresja logistyczna: 0.8213783403656821
Decision Tree: 0.9845288326300985
Epoch 1/50
23/23 [==============================] - 1s 2ms/step - loss: 0.6920 - accuracy: 0.6245
Epoch 2/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6893 - accuracy: 0.6245
Epoch 3/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6842 - accuracy: 0.6245
Epoch 4/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6731 - accuracy: 0.6245
Epoch 5/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6459 - accuracy: 0.6245
Epoch 6/50
23/23 [==============================] - 0s 3ms/step - loss: 0.6261 - accuracy: 0.6245
Epoch 7/50
23/23 [==============================] - 0s 3ms/step - loss: 0.6186 - accuracy: 0.6245
Epoch 8/50
23/23 [==============================] - 0s 2ms/step - loss: 0.6135 - accuracy: 0.6245
Epoch 9/50
23/23 [==============================] - 0s 3ms/step - loss: 0.6089 - accuracy: 0.6245
Epoch 10/5

In [ ]:
y1_predict = forest.predict(X_test)
print("Random Forest {0}".format(accuracy_score(y_test, y1_predict)))

y2_predict = lreg.predict(X_test)
print("Logistic Regresion {0}".format(accuracy_score(y_test, y2_predict)))

y3_predict = tree.predict(X_test)
print("Decision Tree {0}".format(accuracy_score(y_test, y3_predict)))

y4_predict = neuralnetwork.predict(X_test)
print("Neural network {0}".format(accuracy_score(y_test, np.round(abs(y4_predict)), normalize=True)))

Random Forest 0.7640449438202247
Logistic Regresion 0.7134831460674157
Decision Tree 0.7752808988764045
Neural network 0.7191011235955056


#### 2. Poszukaj informacji dotyczących możliwości generowania confusion matrix w tensorflow, wygeneruj ją dla każdego z czterech modeli. Który z modeli jest "bardziej skłonny" do popełniania błędów I rodzaju?

In [ ]:
from sklearn.metrics import confusion_matrix

predict_x = neuralnetwork.predict(X_test)
classes_x = np.round(predict_x)
print(classes_x)

confusion_matrix(classes_x, y_test)

[[1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.

array([[87, 32],
       [18, 41]])

In [ ]:
predict_x1 = lreg.predict(X_test)
classes_x1 = np.round(predict_x1)
print(classes_x1)

confusion_matrix(classes_x1, y_test)

[1 0 1 0 0 0 0 0 1 0 0 1 1 0 1 0 1 1 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0
 0 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 1 0 1 1 1 0 0 1 0 0 0 0 0 1 1 0 1 1 0 0 1
 0 0 0 0 1 0 0 1 1 1 1 1 0 0 0 0 0 1 1 0 0 1 1 1 0 1 0 1 0 1 0 1 0 0 0 1 1
 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 0 1 0 1 1
 0 0 0 0 1 0 0 0 1 1 1 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 1]


array([[84, 30],
       [21, 43]])

In [ ]:
predict_x2 = forest.predict(X_test)
classes_x2 = np.round(predict_x2)
print(classes_x2)

confusion_matrix(classes_x2, y_test)

[1 0 1 1 0 0 0 1 0 1 0 1 1 0 1 0 1 0 0 1 0 1 1 0 0 0 0 0 1 0 1 0 0 1 0 0 0
 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 1 0 0 0 1 1 1 1 1 0 0 1
 0 1 0 0 1 0 0 1 1 1 1 0 0 0 0 0 0 1 1 0 0 1 1 1 0 1 0 1 0 1 0 1 0 0 0 1 1
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 1 0 1 0 0 1
 0 0 0 0 1 0 0 0 1 1 1 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 0 1]


array([[90, 27],
       [15, 46]])

In [ ]:
predict_x3 = tree.predict(X_test)
classes_x3 = np.round(predict_x3)
print(classes_x3)

confusion_matrix(classes_x3, y_test)

[0 0 1 1 0 0 0 0 0 1 0 1 1 0 1 0 1 1 0 1 0 1 1 0 0 1 0 0 1 0 1 0 0 1 0 0 0
 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 1 0 1 0 0 0 0 1 1 0 0 0 0 1
 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 0 0 1 1 0 1 1 1 1 0 1 0 1 0 1 0 1 0 0 0 1 1
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 1 1 1 0 0 1
 0 0 0 0 1 0 0 1 1 1 1 0 1 0 1 0 0 1 0 1 1 1 0 0 0 0 0 0 1 1]


array([[89, 24],
       [16, 49]])

lreg ma najwięcej błędów 1 stopnia

#### 3. Dokładność klasyfikacji nie jest najlepszą metryką w przypadku porównywania ze sobą różnych modeli. Do tego celu bardziej nadaje się metryka F-1. Podaj wyniki F-1 dla każdego modelu i wskaż, który z nich jest najlepszy. Czy najlepszy wynik F-1 występuje również w przypadku modelu, który cechował się najwyższą dokładnością?

In [ ]:
classification_report(classes_x, y_test)

'              precision    recall  f1-score   support\n\n         0.0       0.83      0.73      0.78       119\n         1.0       0.56      0.69      0.62        59\n\n    accuracy                           0.72       178\n   macro avg       0.70      0.71      0.70       178\nweighted avg       0.74      0.72      0.73       178\n'

In [ ]:
classification_report(classes_x1, y_test)

'              precision    recall  f1-score   support\n\n           0       0.80      0.74      0.77       114\n           1       0.59      0.67      0.63        64\n\n    accuracy                           0.71       178\n   macro avg       0.69      0.70      0.70       178\nweighted avg       0.72      0.71      0.72       178\n'

In [ ]:
classification_report(classes_x2, y_test)

'              precision    recall  f1-score   support\n\n           0       0.86      0.77      0.81       117\n           1       0.63      0.75      0.69        61\n\n    accuracy                           0.76       178\n   macro avg       0.74      0.76      0.75       178\nweighted avg       0.78      0.76      0.77       178\n'

In [ ]:
classification_report(classes_x3, y_test)

'              precision    recall  f1-score   support\n\n           0       0.85      0.79      0.82       113\n           1       0.67      0.75      0.71        65\n\n    accuracy                           0.78       178\n   macro avg       0.76      0.77      0.76       178\nweighted avg       0.78      0.78      0.78       178\n'